package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newInstallHookCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "install-hook",
		Short: "在 .git/hooks/pre-commit 安装 stdagent status --strict 检查",
		RunE: func(cmd *cobra.Command, _ []string) error {
			_, root := resolveConfigPath()
			gitDir := filepath.Join(root, ".git")
			if _, err := os.Stat(gitDir); err != nil {
				if errors.Is(err, fs.ErrNotExist) {
					return fmt.Errorf("not a git repository (no .git/ found at %s)", root)
				}
				return err
			}
			hooksDir := filepath.Join(gitDir, "hooks")
			if err := os.MkdirAll(hooksDir, 0o750); err != nil {
				return err
			}
			hookPath := filepath.Join(hooksDir, "pre-commit")
			if _, err := os.Stat(hookPath); err == nil && !force {
				return fmt.Errorf("%s already exists; use --force to overwrite", hookPath)
			}
			content := `#!/bin/sh
# Generated by stdagent install-hook
# Aborts commit if any stdagent-managed file has drifted.
set -e
if ! command -v stdagent >/dev/null 2>&1; then
  echo "stdagent: pre-commit hook installed but stdagent binary not in PATH; skipping" >&2
  exit 0
fi
exec stdagent status --strict
`
			if err := os.WriteFile(hookPath, []byte(content), 0o700); err != nil { //nolint:gosec // pre-commit 必须可执行
				return err
			}
			cmd.Printf("Installed pre-commit hook at %s\n", hookPath)
			cmd.Println("Run `stdagent fix` to repair any drift before committing.")
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "已存在 pre-commit 时覆盖")
	return cmd
}
