---
description: Conventional Commits 1.0.0 风格
---
<!-- Generated by stdagent dev. Source: .stdai/standards/rules/commit-style.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->
# Commit style

Conventional Commits 1.0.0：`<type>(scope): <description>`

- type：`feat` / `fix` / `docs` / `style` / `refactor` / `perf` / `test` / `build` / `ci` / `chore`
- scope 用模块名（`writer` / `runner` / `transformer` / `cli` 等），跨多模块的写宽 scope（如 `claude-code` / `release`）
- description 用中文或英文都行，与现有 commit 史保持一致即可
- 破坏性变更加 `!`：`feat(api)!: 移除旧接口`，并在 body 写 `BREAKING CHANGE:` 段
- 不要 `Co-Authored-By` / AI 署名

参考既有提交风格：

```
fix(writer): 复用 h 变量比较，消除 staticcheck SA4000
refactor(writer): marker 移除 timestamp，输出 deterministic
fix(claude-code): 用 paths 字段而非 applyTo（官方文档要求）
fix(release): ignore CHANGELOG_LATEST.md so goreleaser sees clean tree
```

`.env` / 密钥类文件告知用户，不自作主张提交。staged 文件用 `git add <file>` 显式列出，避免 `git add -A` 把无关文件带进去。
<!-- /Generated by stdagent -->
