---
description: 已推送分支禁止改写历史
---
<!-- Generated by stdagent dev. Source: .stdai/standards/rules/no-history-rewrite.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->
# 已推送分支禁止改写历史

违反任一条立即修复，不辩解。

- FAIL：已推送分支 `git commit --amend` + `git push --force` / `--force-with-lease`
- FAIL：已推送分支 `git rebase` + `git push --force` / `--force-with-lease`
- FAIL：`git reset --hard <older>` + `git push --force` 到已推送分支

修补已推送 commit 的唯一方式：**追加新 commit + fast-forward push**。PR 多一个 commit 不干净也比改写历史好。

唯一例外：本人独占的 WIP 分支，且明确告知协作者后才 amend。`main` / 受保护分支永远不允许 force-push。

发版相关：tag 一旦 push 到 origin 触发了 goreleaser 也不要删。要修复用更高 patch 版本（v0.0.X+1）覆盖。
<!-- /Generated by stdagent -->
