<!-- Generated by stdagent dev. Source: .stdai/standards/root.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->
# std-agent

`stdagent` 是纯 Go CLI，以 `.stdai/` 为单一真相源，将 rules、skills、commands、references 和 subagents 转换为 23 个 AI CLI target 的原生配置。本仓库是其源码并用自身规则自举。

## 结构

- `cmd/stdagent/`：程序入口。
- `internal/cli/`、`config/`、`parser/`、`source/`：命令、配置与源文档读取。
- `internal/transformer/`：协议层和 target adapter。
- `internal/runner/`、`writer/`、`state/`、`budget/`：同步、原子写入、状态和上下文预算。
- `docs/`：格式、架构及各 target 的官方证据。

技术栈：Go 1.26、Cobra、BurntSushi/toml、goccy/go-yaml、doublestar、GoReleaser；工具链由 `mise` 管理。

## 关键约束

- `.stdai/standards/` 是 AI 配置源。生成的 `CLAUDE.md`、`AGENTS.md` 和 target 目录只通过 `go run ./cmd/stdagent sync` 更新。
- frontmatter、协议或 target 映射属于跨 23 个 target 的兼容性变更，必须对照 `docs/format-spec.md`、`docs/conversion-rules.md` 和对应 `docs/targets/` 证据。
- 多 target 共享同一路径时，内容必须字节一致；`AGENTS.md` 是 target-neutral 的共享 rules 层，target 专属能力写入各自 sidecar。

## Done means

相关回归测试已覆盖，且以下命令通过：

```bash
mise run check
go run ./cmd/stdagent sync --no-pull --strict
go run ./cmd/stdagent status
```
<!-- /Generated by stdagent -->
