package source

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/StringKe/std-agent/internal/config"
)

// 外部产物自动采用（auto-adopt）：把项目里已存在的第三方 AI 产物映射为 std 源文件。
//
// 映射规则：
//  1. .ai/guidelines/**/*.md              -> rules, 目标 external/guidelines/<rel>
//  2. .ai/rules/**/*.md                   -> rules, 目标 external/rules/<rel>
//     （源文件自带 globs/applyTo frontmatter 时 parser 自动合并为 ApplyTo）
//  3. .ai/skills/<name>.md（单文件）       -> skills, 目标 external/skills/<name>/SKILL.md，合成 frontmatter
//  4. .ai/skills/<pkg>/SKILL.md（+ 辅助文件）-> skills, 目标 external/skills/<pkg>/...
//  5. .agents/skills/<pkg>/SKILL.md（+ 辅助文件）-> skills, 目标 external/skills/<pkg>/...
//     （与规则 3/4 同名冲突时 .ai 优先，.agents 侧跳过并报 warning）
//  6. 项目根 .mcp.json                    -> 合并进 .stdai/standards/mcp.json 的 servers（仅补缺失 key）
//
// 所有 markdown 产物保证含有效 frontmatter（type/name/description 缺失才合成，
// 原有字段逐字节保留），并注入 provenance（external_source / external_path）。
// 非 markdown 的 skill 辅助文件（scripts/*.sh 等）原样采用。
// 输出按 Path 排序，保证确定性。

// External provenance frontmatter keys.
const (
	provenanceSourceKey = "external_source"
	provenancePathKey   = "external_path"
	// generatedMarker 标识 stdagent 生成物；扫描时跳过，避免把上次 sync 的
	// 输出（如带 footer 的 SKILL.md）当作新的外部源重复采用。
	// 没有 marker 的生成物（如 skill 辅助文件）靠 SkipPaths（上次 sync 的
	// tracked outputs）过滤，见 ExternalScanOptions。
	generatedMarker = "Generated by stdagent"
)

// ExternalScanOptions 控制外部扫描的保守过滤。零值 = 全部采用（历史行为）。
type ExternalScanOptions struct {
	// SkipPaths 是项目相对 slash 路径到上次 sync 记录 sha 的映射。
	// 命中且磁盘内容与记录一致时不采用：stdagent 不吃自己写出的文件。
	// 磁盘内容与记录不一致说明有外部改写（如 Boost 更新），放行重新采用并 warning。
	// 空 sha 表示无条件跳过（调用方无 state 时使用）。
	SkipPaths map[string]string
	// UserSkills 是本地源已拥有的 skill 名（kebab 归一后）。
	// 同名外部包整体跳过并 warning：显式源优先，避免同名双源造成 output collision。
	UserSkills map[string]bool
}

// isGenerated 判断是否为 stdagent 生成物（带 marker 的输出文件）
func isGenerated(raw []byte) bool {
	return len(raw) > 0 && strings.Contains(string(raw), generatedMarker)
}

// ScanExternal 扫描 projectRoot 下的外部产物，返回 Path 已重写为
// external/... 的内存 File 列表（不写盘）。目录缺失视为无产物，不报错。
func ScanExternal(projectRoot string, opts ExternalScanOptions) ([]File, []string, error) {
	s := &externalScanner{root: projectRoot, opts: opts}
	files, warns, err := s.scan()
	if err != nil {
		return nil, warns, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, warns, nil
}

// ImportExternal 把 ScanExternal 结果落盘到 .stdai/standards/external/，
// 并把根 .mcp.json 合并进 .stdai/standards/mcp.json。
// 已是最新（字节一致）的文件跳过；dryRun 只汇报不写盘。
// 返回本次写入（或 dryRun 下将写入）的相对路径列表。
func ImportExternal(projectRoot string, dryRun bool, opts ExternalScanOptions) ([]string, []string, error) {
	files, warns, err := ScanExternal(projectRoot, opts)
	if err != nil {
		return nil, warns, err
	}
	var adopted []string
	for _, f := range files {
		dest := filepath.Join(projectRoot, ".stdai", "standards", filepath.FromSlash(f.Path))
		exist, rerr := os.ReadFile(dest) //nolint:gosec // 路径由 ScanExternal 生成，限定在 .stdai/standards 下
		if rerr == nil && string(exist) == string(f.Raw) {
			continue
		}
		if rerr != nil && !os.IsNotExist(rerr) {
			return adopted, warns, fmt.Errorf("read %s: %w", dest, rerr)
		}
		if !dryRun {
			if err := os.MkdirAll(filepath.Dir(dest), 0o750); err != nil {
				return adopted, warns, fmt.Errorf("mkdir %s: %w", filepath.Dir(dest), err)
			}
			if err := os.WriteFile(dest, f.Raw, 0o600); err != nil {
				return adopted, warns, fmt.Errorf("write %s: %w", dest, err)
			}
		}
		adopted = append(adopted, f.Path)
	}

	// 根 .mcp.json 合并（仅补缺失 servers）
	mcpPath := filepath.Join(projectRoot, ".stdai", "standards", "mcp.json")
	var mcp config.MCPConfig
	var existing []byte
	if data, rerr := os.ReadFile(mcpPath); rerr == nil { //nolint:gosec
		if jerr := json.Unmarshal(data, &mcp); jerr != nil {
			warns = append(warns, fmt.Sprintf("mcp.json: %v", jerr))
			return adopted, warns, nil
		}
		existing = data
	} else if !os.IsNotExist(rerr) {
		return adopted, warns, fmt.Errorf("read mcp.json: %w", rerr)
	}
	added, mwarn := AdoptRootMCP(projectRoot, &mcp)
	warns = append(warns, mwarn...)
	// 旧版本写出的 "version": "" 空值做一次性规范化（去掉该键），仅此一次，
	// 避免每次 sync 的 mtime 抖动。
	normalize := existing != nil && hasEmptyVersionKey(existing)
	if added > 0 || normalize {
		if !dryRun {
			out, jerr := json.MarshalIndent(mcp, "", "  ")
			if jerr != nil {
				return adopted, warns, fmt.Errorf("marshal mcp.json: %w", jerr)
			}
			out = append(out, '\n')
			if err := os.MkdirAll(filepath.Dir(mcpPath), 0o750); err != nil {
				return adopted, warns, fmt.Errorf("mkdir %s: %w", filepath.Dir(mcpPath), err)
			}
			if err := os.WriteFile(mcpPath, out, 0o600); err != nil {
				return adopted, warns, fmt.Errorf("write mcp.json: %w", err)
			}
		}
		if added > 0 {
			adopted = append(adopted, "mcp.json")
		}
	}
	return adopted, warns, nil
}

// hasEmptyVersionKey 报告 mcp.json 是否带有旧版本写出的 "version": "" 空值
func hasEmptyVersionKey(raw []byte) bool {
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return false
	}
	v, ok := top["version"]
	if !ok {
		return false
	}
	var s string
	if err := json.Unmarshal(v, &s); err != nil {
		return false
	}
	return s == ""
}

// AdoptRootMCP 把项目根 .mcp.json 的 servers 合并进 mcp（仅补缺失 key）。
// 支持 std 形状 {"servers": {...}} 与 Claude/Cursor 形状 {"mcpServers": {...}}。
// 根文件不存在返回 added=0；mcp 为 nil 时自动初始化。返回新增 server 数与 warnings。
func AdoptRootMCP(projectRoot string, mcp *config.MCPConfig) (int, []string) {
	if mcp == nil {
		return 0, nil
	}
	raw, err := os.ReadFile(filepath.Join(projectRoot, ".mcp.json")) //nolint:gosec
	if err != nil {
		if !os.IsNotExist(err) {
			return 0, []string{fmt.Sprintf(".mcp.json: %v", err)}
		}
		return 0, nil
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return 0, []string{fmt.Sprintf(".mcp.json: %v", err)}
	}
	serversRaw, ok := top["servers"]
	if !ok {
		serversRaw, ok = top["mcpServers"]
	}
	if !ok {
		return 0, []string{".mcp.json: no servers/mcpServers key, skipped"}
	}
	var servers map[string]config.MCPServer
	if err := json.Unmarshal(serversRaw, &servers); err != nil {
		// mcpServers 形状的值字段可能含未知键，降级为通用 map 转换
		var generic map[string]map[string]interface{}
		if gerr := json.Unmarshal(serversRaw, &generic); gerr != nil {
			return 0, []string{fmt.Sprintf(".mcp.json: %v", gerr)}
		}
		servers = make(map[string]config.MCPServer, len(generic))
		for name, g := range generic {
			servers[name] = genericMCPServer(g)
		}
	}
	// 直接 unmarshal 成功时 Type 可能缺失（mcpServers 形状无 type 键），按 command/url 补齐
	for name, srv := range servers {
		if srv.Type == "" {
			switch {
			case srv.Command != "":
				srv.Type = "stdio"
			case srv.URL != "":
				srv.Type = "http"
			default:
				srv.Type = "stdio"
			}
			servers[name] = srv
		}
	}
	if mcp.Servers == nil {
		mcp.Servers = map[string]config.MCPServer{}
	}
	added := 0
	for name, srv := range servers {
		if _, exists := mcp.Servers[name]; exists {
			continue
		}
		mcp.Servers[name] = srv
		added++
	}
	return added, nil
}

// genericMCPServer 把 mcpServers 风格的通用 map 转为 MCPServer。
// 有 command 视为 stdio，有 url 视为 http，否则保留 env 并置 type=stdio。
func genericMCPServer(g map[string]interface{}) config.MCPServer {
	var srv config.MCPServer
	str := func(k string) string {
		if v, ok := g[k].(string); ok {
			return v
		}
		return ""
	}
	if cmd := str("command"); cmd != "" {
		srv.Type = "stdio"
		srv.Command = cmd
		if args, ok := g["args"].([]interface{}); ok {
			for _, a := range args {
				if s, ok := a.(string); ok {
					srv.Args = append(srv.Args, s)
				}
			}
		}
	} else if url := str("url"); url != "" {
		srv.Type = "http"
		srv.URL = url
	}
	if srv.Type == "" {
		srv.Type = "stdio"
	}
	if env, ok := g["env"].(map[string]interface{}); ok {
		srv.Env = map[string]string{}
		for k, v := range env {
			if s, ok := v.(string); ok {
				srv.Env[k] = s
			}
		}
	}
	if len(srv.Env) == 0 {
		srv.Env = nil
	}
	return srv
}

// externalScanner 持有扫描状态（已占 dest 集合用于跨源去重）
type externalScanner struct {
	root  string
	opts  ExternalScanOptions
	seen  map[string]bool
	warns []string
	// skippedSelf 统计命中 SkipPaths 的自生成文件数，scan 末尾汇总为一条 warning
	skippedSelf int
}

// skipSelf 报告项目相对路径是否为"未被外部改写的"上次 sync 输出。
// 路径命中且磁盘内容与记录 sha 一致时计数并返回 true，调用方跳过该候选。
// 磁盘内容与记录不一致时返回 false（放行重新采用）并 warning：
// 上游改写不能静默丢掉，也不能静默覆盖，重新采用后由 transformer 正常渲染。
func (s *externalScanner) skipSelf(projectPath string) bool {
	want, ok := s.opts.SkipPaths[filepath.ToSlash(projectPath)]
	if !ok {
		return false
	}
	if want != "" {
		raw, err := os.ReadFile(filepath.Join(s.root, filepath.FromSlash(projectPath))) //nolint:gosec // 路径来自受控扫描
		if err == nil && sha256Hex(raw) != want {
			s.warns = append(s.warns, fmt.Sprintf("[external] %s changed outside stdagent, re-adopting as update", filepath.ToSlash(projectPath)))
			return false
		}
	}
	s.skippedSelf++
	return true
}

// sha256Hex 返回内容的 SHA256 hex
func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// shadowed 报告 skill 包名是否已被本地显式源占用。
// 是则 warning 并返回 true，调用方应整体跳过该外部包。
// 仅用于单文件 skill（已确认是新增外部内容）；整包走 discardIfShadowed。
func (s *externalScanner) shadowed(origin, pkg string) bool {
	if s.opts.UserSkills[kebab(pkg)] {
		s.warns = append(s.warns, fmt.Sprintf("[external] %s/%s shadows user skill %q, skipped", origin, pkg, kebab(pkg)))
		return true
	}
	return false
}

// discardIfShadowed 在整包扫描后判定：包内经自生成过滤仍有剩余文件、
// 且包名被本地显式源占用时 warning 并返回 true（调用方丢弃整包）。
// 全包都是自生成物时静默跳过，避免每次 sync 对自有输出重复报 shadow 噪音。
func (s *externalScanner) discardIfShadowed(origin, pkg string, pkgFiles []File) bool {
	if len(pkgFiles) == 0 || !s.opts.UserSkills[kebab(pkg)] {
		return false
	}
	s.warns = append(s.warns, fmt.Sprintf("[external] %s/%s shadows user skill %q, skipped", origin, pkg, kebab(pkg)))
	return true
}

// scan 按固定顺序执行各源扫描（.ai 优先于 .agents，保证冲突时 .ai 胜出）
func (s *externalScanner) scan() ([]File, []string, error) {
	s.seen = map[string]bool{}
	var out []File

	// 1/2. .ai/guidelines + .ai/rules -> rules
	for _, src := range []struct {
		dir    string
		dest   string
		origin string
	}{
		{".ai/guidelines", "external/guidelines", ".ai/guidelines"},
		{".ai/rules", "external/rules", ".ai/rules"},
	} {
		files, err := s.scanRulesDir(src.dir, src.dest, src.origin)
		if err != nil {
			return nil, s.warns, err
		}
		out = append(out, files...)
	}

	// 3/4. .ai/skills（单文件合成 + 整包原样）
	files, err := s.scanAiSkills()
	if err != nil {
		return nil, s.warns, err
	}
	out = append(out, files...)

	// 5. .agents/skills（整包原样，冲突跳过）
	files, err = s.scanSkillPackages(".agents/skills", ".agents/skills")
	if err != nil {
		return nil, s.warns, err
	}
	out = append(out, files...)

	if s.skippedSelf > 0 {
		s.warns = append(s.warns, fmt.Sprintf("[external] skipped %d self-generated files (tracked sync outputs)", s.skippedSelf))
	}
	return out, s.warns, nil
}

// scanRulesDir 扫描 srcDir 下所有 markdown 为 rules。
// index.md 是包管理器的发现索引而非规则，跳过；命中 SkipPaths 的自生成文件跳过。
func (s *externalScanner) scanRulesDir(srcDir, destPrefix, origin string) ([]File, error) {
	entries, err := collectMarkdown(s.root, srcDir)
	if err != nil {
		return nil, err
	}
	var out []File
	for _, e := range entries {
		if strings.EqualFold(filepath.Base(e.rel), "index.md") {
			s.warns = append(s.warns, fmt.Sprintf("[external] %s/%s is a discovery index, skipped", origin, e.rel))
			continue
		}
		if s.skipSelf(srcDir + "/" + e.rel) {
			continue
		}
		if isGenerated(e.raw) {
			continue
		}
		dest := destPrefix + "/" + e.rel
		if s.claim(dest, origin, e.rel) {
			continue
		}
		raw := ensureProvenance(e.raw, "rules", filenameStem(e.rel), "Adopted from "+origin+"/"+e.rel, origin, e.rel)
		out = append(out, File{Path: dest, Raw: raw})
	}
	return out, nil
}

// scanAiSkills 处理 .ai/skills：顶层单 .md 文件合成 SKILL.md，子目录整包采用
func (s *externalScanner) scanAiSkills() ([]File, error) {
	base := filepath.Join(s.root, ".ai", "skills")
	info, err := os.Stat(base)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat .ai/skills: %w", err)
	}
	if !info.IsDir() {
		// .ai/skills 是单文件 -> 视为单 skill 包
		if s.skipSelf(".ai/skills") {
			return nil, nil
		}
		raw, rerr := os.ReadFile(base) //nolint:gosec
		if rerr != nil {
			return nil, fmt.Errorf("read .ai/skills: %w", rerr)
		}
		if isGenerated(raw) {
			return nil, nil
		}
		name := "skills"
		dest := "external/skills/" + name + "/SKILL.md"
		if s.claim(dest, ".ai/skills", "SKILL.md") {
			return nil, nil
		}
		return []File{{Path: dest, Raw: ensureProvenance(raw, "skills", name, "Adopted from .ai/skills", ".ai/skills", "SKILL.md")}}, nil
	}
	dirents, err := os.ReadDir(base)
	if err != nil {
		return nil, fmt.Errorf("read .ai/skills: %w", err)
	}
	var out []File
	for _, de := range dirents {
		name := de.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		full := filepath.Join(base, name)
		if !de.IsDir() {
			if !isMarkdown(name) {
				continue
			}
			// 单文件 skill：foo.md -> skills/foo/SKILL.md
			if s.skipSelf(".ai/skills/" + name) {
				continue
			}
			raw, rerr := os.ReadFile(full) //nolint:gosec
			if rerr != nil {
				return nil, fmt.Errorf("read %s: %w", full, rerr)
			}
			if isGenerated(raw) {
				continue
			}
			pkg := filenameStem(name)
			if s.shadowed(".ai/skills", pkg) {
				continue
			}
			dest := "external/skills/" + pkg + "/SKILL.md"
			if s.claim(dest, ".ai/skills", name) {
				continue
			}
			raw = ensureProvenance(raw, "skills", kebab(pkg), "Adopted from .ai/skills/"+name, ".ai/skills", name)
			out = append(out, File{Path: dest, Raw: raw})
			continue
		}
		// 子目录整包（先过滤自生成文件，再判 shadow，避免自有输出的重复噪音）
		pkgFiles, perr := s.scanOneSkillPackage(filepath.Join(".ai", "skills", name), "external/skills/"+name, ".ai/skills")
		if perr != nil {
			return nil, perr
		}
		if s.discardIfShadowed(".ai/skills", name, pkgFiles) {
			continue
		}
		out = append(out, pkgFiles...)
	}
	return out, nil
}

// scanSkillPackages 整包采用 <srcDir>/<pkg>/ 下的 skill 包（SKILL.md + 辅助文件）
//
// 跳过项（均为 stdagent 自身管理路径，误采用会与 sync 输出/孤儿清理打架）：
//   - .agents/skills 下的 cmd-* 目录：v3 前 command-as-skill 遗留，由 legacy prune 清理
func (s *externalScanner) scanSkillPackages(srcDir, origin string) ([]File, error) {
	base := filepath.Join(s.root, filepath.FromSlash(srcDir))
	dirents, err := os.ReadDir(base)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", srcDir, err)
	}
	var out []File
	for _, de := range dirents {
		if !de.IsDir() || strings.HasPrefix(de.Name(), ".") {
			continue
		}
		if origin == ".agents/skills" && strings.HasPrefix(de.Name(), "cmd-") {
			s.warns = append(s.warns, fmt.Sprintf("[external] %s/%s is a legacy cmd-* path, left to prune", origin, de.Name()))
			continue
		}
		pkgFiles, perr := s.scanOneSkillPackage(srcDir+"/"+de.Name(), "external/skills/"+de.Name(), origin)
		if perr != nil {
			return nil, perr
		}
		if s.discardIfShadowed(origin, de.Name(), pkgFiles) {
			continue
		}
		out = append(out, pkgFiles...)
	}
	return out, nil
}

// scanOneSkillPackage 采用单个 skill 包目录：SKILL.md（等价主文件）注入 provenance，
// 其余文件原样。包内无 SKILL.md 时顶层单 .md 文件提升为 SKILL.md。
func (s *externalScanner) scanOneSkillPackage(srcDir, destPrefix, origin string) ([]File, error) {
	base := filepath.Join(s.root, filepath.FromSlash(srcDir))
	var rels []string
	err := filepath.WalkDir(base, func(p string, d fs.DirEntry, werr error) error {
		if werr != nil {
			return werr
		}
		if d.IsDir() {
			if strings.HasPrefix(d.Name(), ".") && p != base {
				return filepath.SkipDir
			}
			return nil
		}
		rel, _ := filepath.Rel(base, p)
		rels = append(rels, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("walk %s: %w", srcDir, err)
	}
	sort.Strings(rels)

	hasMain := false
	for _, rel := range rels {
		if isSkillMainFile(rel) {
			hasMain = true
			break
		}
	}
	var out []File
	for _, rel := range rels {
		if s.skipSelf(filepath.ToSlash(srcDir) + "/" + rel) {
			continue
		}
		raw, rerr := os.ReadFile(filepath.Join(base, filepath.FromSlash(rel))) //nolint:gosec
		if rerr != nil {
			return nil, fmt.Errorf("read %s/%s: %w", srcDir, rel, rerr)
		}
		if isGenerated(raw) {
			continue
		}
		if isNestedSkillMain(rel) {
			continue
		}
		destRel := rel
		content := raw
		if isSkillMainFile(rel) {
			content = ensureProvenance(raw, "skills", kebab(packageName(destPrefix)), "Adopted from "+origin+"/"+rel, origin, rel)
		} else if !hasMain && isTopSingleMarkdown(rel, rels) {
			// 无主文件的包：唯一顶层 .md 提升为 SKILL.md
			destRel = "SKILL.md"
			content = ensureProvenance(raw, "skills", kebab(packageName(destPrefix)), "Adopted from "+origin+"/"+rel, origin, rel)
		}
		// 其余文件（非 markdown 辅助、skill 子目录 .md）一律原样，parser 按 SkillFile 关联
		dest := destPrefix + "/" + destRel
		if s.claim(dest, origin, rel) {
			continue
		}
		out = append(out, File{Path: dest, Raw: content})
	}
	return out, nil
}

// claim 标记 dest 已被占用；返回 true 表示调用方应跳过（冲突，后到者让路并 warning）
func (s *externalScanner) claim(dest, origin, rel string) bool {
	if s.seen[dest] {
		s.warns = append(s.warns, fmt.Sprintf("[external] %s/%s conflicts with an earlier source, skipped", origin, rel))
		return true
	}
	s.seen[dest] = true
	return false
}

// mdEntry 是收集到的单个 markdown 文件
type mdEntry struct {
	rel string
	raw []byte
}

// collectMarkdown 收集 srcDir（相对 projectRoot）下所有 markdown 文件
func collectMarkdown(projectRoot, srcDir string) ([]mdEntry, error) {
	base := filepath.Join(projectRoot, filepath.FromSlash(srcDir))
	var out []mdEntry
	err := filepath.WalkDir(base, func(p string, d fs.DirEntry, werr error) error {
		if werr != nil {
			return werr
		}
		if d.IsDir() {
			if strings.HasPrefix(d.Name(), ".") && p != base {
				return filepath.SkipDir
			}
			return nil
		}
		if !isMarkdown(d.Name()) {
			return nil
		}
		rel, _ := filepath.Rel(base, p)
		rel = filepath.ToSlash(rel)
		raw, rerr := os.ReadFile(p) //nolint:gosec
		if rerr != nil {
			return fmt.Errorf("read %s: %w", p, rerr)
		}
		out = append(out, mdEntry{rel: rel, raw: raw})
		return nil
	})
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("walk %s: %w", srcDir, err)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].rel < out[j].rel })
	return out, nil
}

// isSkillMainFile 判断是否为 skill 包主文件（包顶层 SKILL.md，不区分大小写）。
// 子目录里的 SKILL.md（如 .agents/skills/commands/<cmd>/SKILL.md）是 stdagent
// 生成的 command-as-skill 树，绝不视为外部源。
func isSkillMainFile(rel string) bool {
	return !strings.Contains(rel, "/") && strings.EqualFold(filepath.Base(rel), "SKILL.md")
}

// isNestedSkillMain 判断是否为包子目录里的 SKILL.md（生成树特征，跳过）
func isNestedSkillMain(rel string) bool {
	return strings.Contains(rel, "/") && strings.EqualFold(filepath.Base(rel), "SKILL.md")
}

// isTopSingleMarkdown 包内无 SKILL.md 且 rels 中仅此一个顶层 .md 时为 true
func isTopSingleMarkdown(rel string, rels []string) bool {
	if strings.Contains(rel, "/") || !isMarkdown(filepath.Base(rel)) {
		return false
	}
	count := 0
	for _, r := range rels {
		if !strings.Contains(r, "/") && isMarkdown(filepath.Base(r)) {
			count++
		}
	}
	return count == 1
}

// packageName 从 destPrefix（external/skills/<pkg>）取包名
func packageName(destPrefix string) string {
	return filepath.Base(filepath.FromSlash(destPrefix))
}

// LocalSkillNames 返回本地源拥有的 skill 名（kebab 归一后集合）。
// 来源：<standards>/skills/ 下各包目录名 + 其 SKILL.md frontmatter 的 name 值。
// 只读 skills/，不读 external/skills/：已采用的外部包更新不受影响。
func LocalSkillNames(standardsDir string) map[string]bool {
	out := map[string]bool{}
	dirents, err := os.ReadDir(filepath.Join(standardsDir, "skills"))
	if err != nil {
		return out
	}
	for _, de := range dirents {
		if !de.IsDir() || strings.HasPrefix(de.Name(), ".") {
			continue
		}
		out[kebab(de.Name())] = true
		raw, rerr := os.ReadFile(filepath.Join(standardsDir, "skills", de.Name(), "SKILL.md")) //nolint:gosec // 目录项来自受控的 standards/skills 扫描
		if rerr != nil {
			continue
		}
		if front, _, ok := splitExternalFrontmatter(raw); ok {
			if name := frontScalarValue(front, "name"); name != "" {
				out[kebab(name)] = true
			}
		}
	}
	return out
}

// frontScalarValue 从 frontmatter 块提取单行 `key: value` 的值（去首尾引号）。
func frontScalarValue(front []byte, key string) string {
	for _, ln := range strings.Split(string(front), "\n") {
		t := strings.TrimSpace(strings.TrimSuffix(ln, "\r"))
		if strings.HasPrefix(t, key+":") {
			return strings.Trim(strings.TrimSpace(strings.TrimPrefix(t, key+":")), `"'`)
		}
	}
	return ""
}

// frontHasKey 报告 frontmatter 块是否含有顶层 key（忽略空行与注释）。
func frontHasKey(front []byte, key string) bool {
	for _, ln := range strings.Split(string(front), "\n") {
		t := strings.TrimSpace(strings.TrimSuffix(ln, "\r"))
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		if strings.HasPrefix(t, key+":") {
			return true
		}
	}
	return false
}

// leadingSpaces 返回行的前导空格数
func leadingSpaces(s string) int {
	return len(s) - len(strings.TrimLeft(s, " "))
}

// translateRulesPaths 把 Boost 风格的 `paths:` 块复制为 parser 可识别的
// `applyTo:`（parser 将其合并为范围 globs）。仅当 frontmatter 有 `paths:`
// 且无 `applyTo:`/`globs:` 时生效；原 `paths:` 键逐字节保留。
// block scalar（| / >）与空值不处理，原样返回。
func translateRulesPaths(front []byte) []byte {
	if !frontHasKey(front, "paths") || frontHasKey(front, "applyTo") || frontHasKey(front, "globs") {
		return front
	}
	lines := strings.Split(string(front), "\n")
	scalar := ""
	var values []string
	for i, ln := range lines {
		t := strings.TrimSpace(strings.TrimSuffix(ln, "\r"))
		if !strings.HasPrefix(t, "paths:") {
			continue
		}
		rest := strings.TrimSpace(strings.TrimPrefix(t, "paths:"))
		if rest != "" {
			if strings.HasPrefix(rest, "|") || strings.HasPrefix(rest, ">") {
				return front
			}
			scalar = rest
		} else {
			indent := leadingSpaces(ln)
			for _, lj := range lines[i+1:] {
				if strings.TrimSpace(lj) == "" {
					break
				}
				if leadingSpaces(lj) <= indent {
					break
				}
				values = append(values, lj)
			}
		}
		break
	}
	if scalar == "" && len(values) == 0 {
		return front
	}
	var b strings.Builder
	b.Write(front)
	if len(front) > 0 && !strings.HasSuffix(string(front), "\n") {
		b.WriteString("\n")
	}
	if scalar != "" {
		b.WriteString("applyTo: " + scalar + "\n")
	} else {
		b.WriteString("applyTo:\n")
		for _, v := range values {
			b.WriteString(v + "\n")
		}
	}
	return []byte(b.String())
}

// ensureProvenance 保证 markdown 含 frontmatter：缺失的 type/name/description 合成，
// 原有字段逐字节保留，并注入 external_source / external_path。
// rules 类型额外做 paths: -> applyTo: 转译（Boost 范围写法）。
func ensureProvenance(raw []byte, fmType, name, desc, src, orig string) []byte {
	front, body, hasFront := splitExternalFrontmatter(raw)
	if !hasFront {
		var b strings.Builder
		b.WriteString("---\n")
		fmt.Fprintf(&b, "type: %s\n", fmType)
		fmt.Fprintf(&b, "name: %s\n", kebab(name))
		fmt.Fprintf(&b, "description: %s\n", yamlSingle(desc))
		fmt.Fprintf(&b, "%s: %s\n", provenanceSourceKey, yamlSingle(src))
		fmt.Fprintf(&b, "%s: %s\n", provenancePathKey, yamlSingle(orig))
		b.WriteString("---\n")
		b.Write(raw)
		return []byte(b.String())
	}
	if fmType == "rules" {
		front = translateRulesPaths(front)
	}
	lines := strings.Split(string(front), "\n")
	has := func(key string) bool {
		for _, ln := range lines {
			trimmed := strings.TrimSpace(ln)
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			if strings.HasPrefix(trimmed, key+":") {
				return true
			}
		}
		return false
	}
	var b strings.Builder
	b.WriteString("---\n")
	if !has("type") {
		fmt.Fprintf(&b, "type: %s\n", fmType)
	}
	if !has("name") {
		fmt.Fprintf(&b, "name: %s\n", kebab(name))
	}
	if !has("description") {
		fmt.Fprintf(&b, "description: %s\n", yamlSingle(desc))
	}
	b.Write(front)
	if len(front) > 0 && !strings.HasSuffix(string(front), "\n") {
		b.WriteString("\n")
	}
	if !has(provenanceSourceKey) {
		fmt.Fprintf(&b, "%s: %s\n", provenanceSourceKey, yamlSingle(src))
	}
	if !has(provenancePathKey) {
		fmt.Fprintf(&b, "%s: %s\n", provenancePathKey, yamlSingle(orig))
	}
	b.WriteString("---\n")
	b.Write(body)
	return []byte(b.String())
}

// splitExternalFrontmatter 拆分 frontmatter（与 parser 语义一致：--- 开头，行首 --- 结束）
func splitExternalFrontmatter(raw []byte) ([]byte, []byte, bool) {
	var rest []byte
	switch {
	case strings.HasPrefix(string(raw), "---\r\n"):
		rest = raw[5:]
	case strings.HasPrefix(string(raw), "---\n"):
		rest = raw[4:]
	default:
		return nil, raw, false
	}
	start := 0
	for {
		idx := strings.Index(string(rest[start:]), "\n")
		var line string
		var next int
		if idx < 0 {
			line = string(rest[start:])
			next = len(rest)
		} else {
			line = string(rest[start : start+idx])
			next = start + idx + 1
		}
		trimmed := strings.TrimSuffix(line, "\r")
		if trimmed == "---" {
			return rest[:start], rest[next:], true
		}
		if idx < 0 {
			return nil, raw, false
		}
		start = next
	}
}

// filenameStem 取文件名去扩展名
func filenameStem(rel string) string {
	base := filepath.Base(rel)
	ext := filepath.Ext(base)
	return strings.TrimSuffix(base, ext)
}

// kebab 转为 kebab-case（小写，_/./空格 -> -）
func kebab(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "_", "-")
	s = strings.ReplaceAll(s, ".", "-")
	s = strings.ReplaceAll(s, " ", "-")
	return s
}

// yamlSingle 把字符串编码为单行 YAML 标量（无换行时尽量裸写，含特殊字符则双引号转义）
func yamlSingle(s string) string {
	if s == "" {
		return `""`
	}
	needsQuote := strings.ContainsAny(s, ":#{}[],&*!|>'\"%@`") || strings.Contains(s, "\n") ||
		strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") || strings.HasPrefix(s, "- ")
	if !needsQuote {
		return s
	}
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString("\\n")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
