package writer

import (
	"fmt"
	"strings"
	"time"
)

// Marker 常量用于 stdagent 文件首尾标记
const (
	MarkerStart = "<!-- Generated by stdagent"
	MarkerEnd   = "<!-- /Generated by stdagent -->"
)

// FooterOptions 控制 footer 注入
type FooterOptions struct {
	Inject       bool
	InjectWhatIs bool
	Version      string
	SourcePath   string // 相对 .stdai/standards/ 的源路径
	TargetName   string
	GeneratedAt  time.Time
}

// HeaderComment 返回 markdown 文件首部 marker 注释
func HeaderComment(opts FooterOptions) string {
	if !opts.Inject {
		return ""
	}
	at := opts.GeneratedAt.UTC().Format(time.RFC3339)
	src := opts.SourcePath
	if src == "" {
		src = "(generated)"
	}
	return fmt.Sprintf(
		"<!-- Generated by stdagent %s at %s. Source: .stdai/standards/%s. Run `stdagent sync` to regenerate. Do not edit by hand. -->\n",
		opts.Version, at, src,
	)
}

// FooterMarker 返回 markdown 文件末尾 marker，可选追加 About 段
func FooterMarker(opts FooterOptions) string {
	if !opts.Inject {
		return ""
	}
	if opts.InjectWhatIs {
		return whatIsBlock(opts) + "\n" + MarkerEnd + "\n"
	}
	return MarkerEnd + "\n"
}

func whatIsBlock(opts FooterOptions) string {
	var b strings.Builder
	b.WriteString("\n---\n\n## About This File\n\n")
	b.WriteString("This file is part of `stdagent` synchronized AI standards.\n\n")
	if opts.SourcePath != "" {
		fmt.Fprintf(&b, "- **Edit source**: `.stdai/standards/%s`\n", opts.SourcePath)
	}
	b.WriteString("- **Regenerate**: `stdagent sync`\n")
	if opts.TargetName != "" {
		fmt.Fprintf(&b, "- **Disable target**: set `[targets].%s.enabled = false` in `.stdai/config.toml`\n", opts.TargetName)
	}
	b.WriteString("- **Documentation**: https://github.com/StringKe/std-ai\n")
	return b.String()
}

// HasMarker 检查文件内容是否含 stdagent marker
func HasMarker(content []byte) bool {
	return strings.Contains(string(content), MarkerStart)
}

// stripGeneratedMarker 把首个 `<!-- Generated by stdagent ... -->` 注释整体替换为稳定占位符
//
// 用于 writer.Apply 内容等价性比较：marker 含 version + timestamp，每次 sync 都会变，
// 不归一化会导致即使源文档未变也整文件重写，污染 git diff。
//
// 仅替换首个 MarkerStart 注释；MarkerEnd 不带变量值无需处理。
func stripGeneratedMarker(content []byte) []byte {
	s := string(content)
	start := strings.Index(s, MarkerStart)
	if start < 0 {
		return content
	}
	rel := strings.Index(s[start:], "-->")
	if rel < 0 {
		return content
	}
	end := start + rel + len("-->")
	return []byte(s[:start] + "<!-- stdagent-marker -->" + s[end:])
}
