package writer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestApplyWritesNewFile(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)
	plan := &Plan{
		Target: "test",
		Files: []FileOp{
			{Path: "out.md", Content: []byte("hello\n"), Marker: true},
		},
	}
	written, skipped, err := w.Apply(plan)
	if err != nil {
		t.Fatal(err)
	}
	if written != 1 || skipped != 0 {
		t.Errorf("written=%d skipped=%d", written, skipped)
	}
	got, _ := os.ReadFile(filepath.Join(tmp, "out.md"))
	if string(got) != "hello\n" {
		t.Errorf("content = %q", got)
	}
}

func TestApplySkipsUnchanged(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)
	mustWrite(t, filepath.Join(tmp, "x.md"), "same")
	plan := &Plan{
		Files: []FileOp{
			{Path: "x.md", Content: []byte("same")},
		},
	}
	_, skipped, _ := w.Apply(plan)
	if skipped != 1 {
		t.Errorf("skipped = %d", skipped)
	}
}

func TestApplyDryRun(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, true)
	plan := &Plan{
		Files: []FileOp{
			{Path: "x.md", Content: []byte("hello")},
		},
	}
	written, _, _ := w.Apply(plan)
	if written != 0 {
		t.Errorf("dry-run should not write, got %d", written)
	}
	if _, err := os.Stat(filepath.Join(tmp, "x.md")); err == nil {
		t.Error("file should not exist in dry-run")
	}
}

func TestChecksumStable(t *testing.T) {
	a := Checksum([]byte("hello"))
	b := Checksum([]byte("hello"))
	if a != b {
		t.Errorf("checksum should be stable: %s vs %s", a, b)
	}
	if Checksum([]byte("hello!")) == a {
		t.Error("different content should produce different checksum")
	}
}

func TestHeaderAndFooter(t *testing.T) {
	opts := FooterOptions{
		Inject:       true,
		InjectWhatIs: true,
		Version:      "v0.1.0",
		SourcePath:   "rules/coding.md",
		TargetName:   "claude-code",
		GeneratedAt:  time.Date(2026, 5, 8, 0, 0, 0, 0, time.UTC),
	}
	h := HeaderComment(opts)
	if !strings.Contains(h, "Generated by stdagent v0.1.0") {
		t.Errorf("header missing version: %q", h)
	}
	if !strings.Contains(h, "rules/coding.md") {
		t.Errorf("header missing source path: %q", h)
	}
	f := FooterMarker(opts)
	if !strings.Contains(f, "About This File") {
		t.Error("footer missing whatis")
	}
	if !strings.Contains(f, MarkerEnd) {
		t.Error("footer missing close marker")
	}
}

func TestHeaderInjectFalse(t *testing.T) {
	opts := FooterOptions{Inject: false}
	if HeaderComment(opts) != "" {
		t.Error("expected empty header when Inject=false")
	}
	if FooterMarker(opts) != "" {
		t.Error("expected empty footer when Inject=false")
	}
}

func TestHasMarker(t *testing.T) {
	if !HasMarker([]byte(MarkerStart + " v0.1.0 at ... -->")) {
		t.Error("should detect marker")
	}
	if HasMarker([]byte("# Plain markdown\n\nNo marker.")) {
		t.Error("should not detect marker")
	}
}

func TestBackupSnapshot(t *testing.T) {
	tmp := t.TempDir()
	root := filepath.Join(tmp, "proj")
	mustMkdir(t, root)
	mustWrite(t, filepath.Join(root, "CLAUDE.md"), "old content")

	backupDir := filepath.Join(tmp, "backups")
	b := NewBackup(backupDir, 3)
	dir, err := b.Snapshot(root, []string{"CLAUDE.md", "missing.md"})
	if err != nil {
		t.Fatal(err)
	}
	if dir == "" {
		t.Fatal("expected backup dir")
	}
	got, _ := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if string(got) != "old content" {
		t.Errorf("backup content = %q", got)
	}
}

func TestBackupSnapshotEmpty(t *testing.T) {
	tmp := t.TempDir()
	root := filepath.Join(tmp, "proj")
	mustMkdir(t, root)
	b := NewBackup(filepath.Join(tmp, "backups"), 3)
	dir, err := b.Snapshot(root, []string{"missing.md"})
	if err != nil {
		t.Fatal(err)
	}
	if dir != "" {
		t.Errorf("expect empty dir when nothing backed up, got %q", dir)
	}
}

func TestBackupPrune(t *testing.T) {
	tmp := t.TempDir()
	b := NewBackup(tmp, 2)

	for _, ts := range []string{
		"2026-01-01T00-00-00Z",
		"2026-02-01T00-00-00Z",
		"2026-03-01T00-00-00Z",
		"2026-04-01T00-00-00Z",
	} {
		dir := filepath.Join(tmp, ts)
		mustMkdir(t, dir)
		mustWrite(t, filepath.Join(dir, "x"), "y")
	}
	if err := b.prune(); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(tmp)
	if len(entries) != 2 {
		t.Errorf("after prune: %d entries, want 2", len(entries))
	}
}

func TestSnapshotMultipleFilesWithMissing(t *testing.T) {
	tmp := t.TempDir()
	proj := filepath.Join(tmp, "proj")
	mustMkdir(t, proj)
	mustMkdir(t, filepath.Join(proj, ".claude/rules"))
	mustWrite(t, filepath.Join(proj, "CLAUDE.md"), "claude-content")
	mustWrite(t, filepath.Join(proj, "AGENTS.md"), "agents-content")
	mustWrite(t, filepath.Join(proj, ".claude/rules/style.md"), "style-content")

	b := NewBackup(filepath.Join(tmp, "backups"), 5)
	dir, err := b.Snapshot(proj, []string{
		"CLAUDE.md",
		"AGENTS.md",
		".claude/rules/style.md",
		"missing-file.md", // 应被跳过
	})
	if err != nil {
		t.Fatal(err)
	}
	if dir == "" {
		t.Fatal("expected non-empty backup dir")
	}
	for _, name := range []string{"CLAUDE.md", "AGENTS.md", ".claude/rules/style.md"} {
		c, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Errorf("backup %s missing: %v", name, err)
			continue
		}
		if len(c) == 0 {
			t.Errorf("backup %s empty", name)
		}
	}
	// missing-file 不应在 backup
	if _, err := os.Stat(filepath.Join(dir, "missing-file.md")); err == nil {
		t.Error("missing-file should not be backed up")
	}
}

func TestApplyMixedWrittenAndSkipped(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)
	mustWrite(t, filepath.Join(tmp, "existing.md"), "same")

	plan := &Plan{
		Files: []FileOp{
			{Path: "new1.md", Content: []byte("new content 1")},
			{Path: "existing.md", Content: []byte("same")}, // skip
			{Path: "subdir/new2.md", Content: []byte("new content 2")},
		},
	}
	written, skipped, err := w.Apply(plan)
	if err != nil {
		t.Fatal(err)
	}
	if written != 2 {
		t.Errorf("written = %d, want 2", written)
	}
	if skipped != 1 {
		t.Errorf("skipped = %d, want 1", skipped)
	}

	// 验证 subdir 自动创建
	if _, err := os.Stat(filepath.Join(tmp, "subdir/new2.md")); err != nil {
		t.Errorf("subdir/new2.md missing: %v", err)
	}
	// 验证 plan.Files[1].Skip 被设置
	if !plan.Files[1].Skip {
		t.Error("existing.md FileOp.Skip should be set")
	}
}

func TestApplySkipsWhenOnlyMarkerTimestampDiffers(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)

	oldHeader := "<!-- Generated by stdagent v0.1.0 at 2026-01-01T00:00:00Z. Source: .stdai/standards/rules/style.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->\n"
	newHeader := "<!-- Generated by stdagent v0.1.0 at 2026-05-10T08:32:11Z. Source: .stdai/standards/rules/style.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->\n"
	body := "# Style\n\nbody content\n<!-- /Generated by stdagent -->\n"
	mustWrite(t, filepath.Join(tmp, "out.md"), oldHeader+body)

	statBefore, _ := os.Stat(filepath.Join(tmp, "out.md"))

	plan := &Plan{
		Files: []FileOp{
			{Path: "out.md", Content: []byte(newHeader + body), Marker: true},
		},
	}
	written, skipped, err := w.Apply(plan)
	if err != nil {
		t.Fatal(err)
	}
	if written != 0 || skipped != 1 {
		t.Errorf("written=%d skipped=%d, want 0/1", written, skipped)
	}
	if !plan.Files[0].Skip || plan.Files[0].Reason != "unchanged" {
		t.Errorf("op = %+v", plan.Files[0])
	}
	statAfter, _ := os.Stat(filepath.Join(tmp, "out.md"))
	if !statBefore.ModTime().Equal(statAfter.ModTime()) {
		t.Errorf("mtime should not change: before=%v after=%v", statBefore.ModTime(), statAfter.ModTime())
	}
	got, _ := os.ReadFile(filepath.Join(tmp, "out.md"))
	if string(got) != oldHeader+body {
		t.Errorf("file content should be untouched, got %q", got)
	}
}

func TestApplyWritesWhenBodyChangesEvenIfMarkerSame(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)
	header := "<!-- Generated by stdagent v0.1.0 at 2026-01-01T00:00:00Z. Source: .stdai/standards/rules/style.md. Run `stdagent sync` to regenerate. Do not edit by hand. -->\n"
	mustWrite(t, filepath.Join(tmp, "out.md"), header+"# Old\n")

	plan := &Plan{
		Files: []FileOp{
			{Path: "out.md", Content: []byte(header + "# New\n"), Marker: true},
		},
	}
	written, skipped, _ := w.Apply(plan)
	if written != 1 || skipped != 0 {
		t.Errorf("written=%d skipped=%d, want 1/0", written, skipped)
	}
}

func TestStripGeneratedMarker(t *testing.T) {
	src := []byte("<!-- Generated by stdagent v0.1.0 at 2026-05-10T08:32:11Z. Source: x. -->\nbody\n")
	got := stripGeneratedMarker(src)
	want := "<!-- stdagent-marker -->\nbody\n"
	if string(got) != want {
		t.Errorf("stripGeneratedMarker = %q, want %q", got, want)
	}

	plain := []byte("# no marker here\nbody\n")
	if string(stripGeneratedMarker(plain)) != string(plain) {
		t.Error("content without marker should be returned as-is")
	}
}

func TestApplySkipPreSet(t *testing.T) {
	tmp := t.TempDir()
	w := NewWriter(tmp, false)
	plan := &Plan{
		Files: []FileOp{
			{Path: "x.md", Content: []byte("x"), Skip: true},
		},
	}
	written, skipped, _ := w.Apply(plan)
	if written != 0 || skipped != 1 {
		t.Errorf("written=%d skipped=%d, want 0/1", written, skipped)
	}
	if _, err := os.Stat(filepath.Join(tmp, "x.md")); err == nil {
		t.Error("file should not be written when Skip=true")
	}
}

func TestFileExistsAndChecksum(t *testing.T) {
	tmp := t.TempDir()
	exists := filepath.Join(tmp, "a.txt")
	mustWrite(t, exists, "hello")
	if !FileExists(exists) {
		t.Error("FileExists should return true")
	}
	if FileExists(filepath.Join(tmp, "nope.txt")) {
		t.Error("FileExists should return false for missing")
	}

	hash := Checksum([]byte("hello"))
	if hash != "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824" {
		t.Errorf("Checksum hello = %s", hash)
	}
}

func mustWrite(t *testing.T, p, c string) {
	t.Helper()
	if err := os.WriteFile(p, []byte(c), 0o600); err != nil {
		t.Fatal(err)
	}
}

func mustMkdir(t *testing.T, p string) {
	t.Helper()
	if err := os.MkdirAll(p, 0o755); err != nil {
		t.Fatal(err)
	}
}
