package transformer

import (
	"fmt"
	"strings"

	"github.com/StringKe/std-agent/internal/config"
	"github.com/StringKe/std-agent/internal/parser"
	"github.com/StringKe/std-agent/internal/transformer/protocol"
	"github.com/StringKe/std-agent/internal/transformer/transformerutil"
	"github.com/StringKe/std-agent/internal/writer"
)

func init() { Register(&Codex{}) }

// Codex 是 OpenAI Codex CLI transformer
type Codex struct{}

// Name 返回 "codex"
func (c *Codex) Name() string { return "codex" }

// Plan 委托 AgentsMD 协议按 codexAdapter 计算输出，并为 subagents 追加
// Codex 原生可消费的 .codex/agents/<name>.toml
// （https://developers.openai.com/codex/subagents，feature flag multi_agent 默认启用）。
//
// 过渡期同时保留 .agents/subagents/<n>.md 降级产物（AgentsMD 协议产出）：
// TOML 是否受 trusted-project 边界限制官方未明说，Markdown 版留作人读文档。
func (c *Codex) Plan(docs []*parser.Document, cfg *config.Config) (*writer.Plan, error) {
	filtered := FilterDocs(docs, c.Name())
	plan, err := protocol.AgentsMD{}.Plan(filtered, codexAdapter, cfg)
	if err != nil {
		return nil, err
	}
	for _, d := range filtered {
		if d.Type == parser.TypeSubagents {
			plan.Files = append(plan.Files, buildCodexAgentTOML(d, cfg))
		}
	}
	return plan, nil
}

// buildCodexAgentTOML 渲染单个 subagent 为 .codex/agents/<name>.toml
//
// 必填字段 name / description / developer_instructions（纯文本指令），
// 可选 model。developer_instructions 用 TOML 多行 literal string（三个单引号），
// 与 gemini commands TOML 同一约定。
func buildCodexAgentTOML(d *parser.Document, cfg *config.Config) writer.FileOp {
	var b strings.Builder
	if cfg.Inject {
		fmt.Fprintf(&b,
			"# Generated by stdagent %s. Source: .stdai/standards/%s. Run `stdagent sync` to regenerate. Do not edit by hand.\n\n",
			transformerutil.Version(), d.Path)
	}
	fmt.Fprintf(&b, "name = %q\n", d.Name)
	fmt.Fprintf(&b, "description = %q\n", d.Description)
	if d.Model != "" {
		fmt.Fprintf(&b, "model = %q\n", d.Model)
	}
	instructions := strings.TrimSpace(d.Body)
	if instructions == "" {
		instructions = "(empty)"
	}
	fmt.Fprintf(&b, "developer_instructions = '''\n%s\n'''\n", instructions)
	return writer.FileOp{
		Path:    transformerutil.FilePath(".codex/agents", d.Name, ".toml"),
		Content: []byte(b.String()),
		Marker:  cfg.Inject,
	}
}

// codexAdapter 配置 AgentsMD 协议族的 codex 变体。
//
// RulesDir 为空：Codex 项目级唯一指令机制是 AGENTS.md（project_doc_max_bytes
// 默认 32768 字节），nonRoot rules 全文 inline（amp / warp 同风格）。曾经的
// RulesDir=".codex/memories" 与官方语义冲突，已废弃：Codex 的 memories 是
// ~/.codex/memories/ 用户级自动记忆系统（无项目级目录，mem v2 起单根），而
// 项目级 .codex/ 是 Team Config 配置目录（config.toml / rules/*.rules
// execpolicy / skills/），且被沙箱与 .git 同级 carveout 保护，不适合放
// markdown 指令。旧产物由 runner 的 legacyCodexMemoriesOrphans 自动清理。
//
// FallbackDir=".agents"：references / subagents 降级落 .agents/<subdir>/，
// 与官方 .agents/skills/（Agent Skills 协议）同命名空间，不与 antigravity
// 的 .agents/rules/ 冲突。
var codexAdapter = protocol.Adapter{
	Name:                  "codex",
	RootFileName:          "AGENTS.md",
	NestedSupported:       true,
	RulesDir:              "",
	SkillsDir:             ".agents/skills",
	FallbackDir:           ".agents",
	InjectExplainer:       true,
	InjectStdaiTypeField:  true,
	SkillSupportedFields:  []string{"name", "description", "license", "compatibility", "metadata"},
	CommandFormat:         protocol.CommandSkillPrefix,
	CommandsAsSkillSubdir: "commands", // v3：子目录隔离（避免 cmd- 私有前缀污染 skill 命名空间）
	InjectCommandsToRoot:  false,
	InjectTypeGlossary:    true,
}
