package transformer

import (
	"fmt"
	"path"
	"strings"

	"std-ai/internal/config"
	"std-ai/internal/parser"
	"std-ai/internal/transformer/transformerutil"
	"std-ai/internal/writer"
)

func init() {
	Register(&Codex{})
}

// Codex 是 OpenAI Codex CLI transformer
type Codex struct{}

// Name 返回 "codex"
func (c *Codex) Name() string { return "codex" }

// Plan 计算输出
func (c *Codex) Plan(docs []*parser.Document, cfg *config.Config) (*writer.Plan, error) {
	plan := &writer.Plan{Target: c.Name()}

	docs = FilterDocs(docs, c.Name())
	if len(docs) == 0 {
		return plan, nil
	}

	rules := transformerutil.FilterByType(docs, parser.TypeRules)
	skills := transformerutil.FilterByType(docs, parser.TypeSkills)
	commands := transformerutil.FilterByType(docs, parser.TypeCommands)
	transformerutil.SortDocs(rules)
	transformerutil.SortDocs(skills)
	transformerutil.SortDocs(commands)

	// 嵌套 root 输出到 <NestedPath>/AGENTS.md（无 manifest）
	topRules, nestedRoots := transformerutil.PartitionNested(rules)
	for _, d := range nestedRoots {
		plan.Files = append(plan.Files, c.buildNestedAGENTSMd(d, cfg))
	}

	main, spilled := c.buildAGENTSMdWithCommands(topRules, commands, cfg)
	plan.Files = append(plan.Files, main)
	for _, sp := range spilled {
		plan.Files = append(plan.Files, c.buildSpillRuleFile(sp, cfg))
	}

	for _, d := range skills {
		plan.Files = append(plan.Files, c.buildSkillFile(d, cfg)...)
	}

	// commands 降级为 skill：codex 自定义 prompt 已 deprecated 但支持 agent skills，
	// 把 std command 写为 .agents/skills/cmd-<n>/SKILL.md，description 加 slash 调用 hint
	for _, d := range commands {
		plan.Files = append(plan.Files, c.buildCommandAsSkill(d, cfg))
	}

	return plan, nil
}

// buildAGENTSMdWithCommands 拼 AGENTS.md，rules 超字节时返回溢出 docs；
// commands 段落始终追加在 AGENTS.md 末尾（让 aider / 其他读 AGENTS.md 的工具也能看到 slash 命令）
func (c *Codex) buildAGENTSMdWithCommands(rules, commands []*parser.Document, cfg *config.Config) (writer.FileOp, []*parser.Document) {
	op, spilled := c.buildAGENTSMd(rules, cfg)
	if len(commands) == 0 {
		return op, spilled
	}
	// 把 commands section 追加到 op.Content 的尾部 marker 之前
	commandsBlock := buildCommandsSection(commands)
	op.Content = injectBeforeFooter(op.Content, commandsBlock)
	return op, spilled
}

// buildCommandsSection 构造 ## Slash Commands 段落
func buildCommandsSection(commands []*parser.Document) string {
	var b strings.Builder
	b.WriteString("\n## Slash Commands\n\n")
	b.WriteString("以下命令可由用户输入 `/<name>` 触发，或在 LLM 对话中描述意图调用。\n\n")
	for _, d := range commands {
		fmt.Fprintf(&b, "### /%s\n\n", d.Name)
		if d.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", d.Description)
		}
		body := strings.TrimSpace(d.Body)
		if body != "" {
			b.WriteString(body)
			b.WriteString("\n\n")
		}
	}
	return b.String()
}

// injectBeforeFooter 把 block 插入到内容尾部，但在 stdagent close marker 之前
func injectBeforeFooter(content []byte, block string) []byte {
	s := string(content)
	// stdagent close marker 形如 "<!-- /Generated by stdagent -->\n"
	const marker = "<!-- /Generated by stdagent -->"
	idx := strings.LastIndex(s, marker)
	if idx < 0 {
		// 无 marker（inject=false），直接追加
		return []byte(s + block)
	}
	return []byte(s[:idx] + block + s[idx:])
}

// buildAGENTSMd 拼 AGENTS.md = root body（项目总结）+ stdagent 自动 manifest 清单。
//
// codex 不支持 @import，所有 nonRoot rule 写到 .codex/memories/<name>.md（codex CLI
// 自动加载该目录所有 .md）。AGENTS.md 头部是 root body（项目总结），尾部是 manifest 段
// 让 AI 看清单时知道有哪些规则文件可读、各做什么。
//
// 返回 op 与 nonRoot rules（caller 写到 .codex/memories/）。root rule 不 fan-out。
func (c *Codex) buildAGENTSMd(rules []*parser.Document, cfg *config.Config) (writer.FileOp, []*parser.Document) {
	opts := transformerutil.MakeOpts(cfg, c.Name(), "", true)
	roots, nonRoot := transformerutil.PartitionRoot(rules)
	var body strings.Builder
	if len(roots) > 0 {
		body.WriteString(transformerutil.RenderRootBody(roots))
	} else {
		body.WriteString("# Project AGENTS Manifest\n\n")
	}
	if len(nonRoot) > 0 {
		body.WriteString(transformerutil.BuildRuleManifestSection(
			"Reference Rules",
			c.Name(),
			nonRoot,
			func(d *parser.Document) string { return transformerutil.FilePath(".codex/memories", d.Name, ".md") },
			false,
		))
	}
	op := transformerutil.BuildMarkdownFile("AGENTS.md", "", body.String(), opts)
	op.IsRoot = true
	return op, nonRoot
}

// buildNestedAGENTSMd 把嵌套 root doc 输出到 <NestedPath>/AGENTS.md，纯 body + marker，无 manifest。
// codex 在该子目录工作时按 codex 自动加载机制叠加加载。
func (c *Codex) buildNestedAGENTSMd(d *parser.Document, cfg *config.Config) writer.FileOp {
	opts := transformerutil.MakeOpts(cfg, c.Name(), d.Path, false)
	op := transformerutil.BuildMarkdownFile(
		path.Join(d.NestedPath, "AGENTS.md"),
		"", d.Body, opts,
	)
	op.IsRoot = true
	return op
}

func (c *Codex) buildSpillRuleFile(d *parser.Document, cfg *config.Config) writer.FileOp {
	opts := transformerutil.MakeOpts(cfg, c.Name(), d.Path, false)
	body := strings.TrimSpace(d.Body)
	if d.Description != "" {
		body = d.Description + "\n\n" + body
	}
	return transformerutil.BuildMarkdownFile(
		transformerutil.FilePath(".codex/memories", d.Name, ".md"),
		"", body, opts,
	)
}

func (c *Codex) buildSkillFile(d *parser.Document, cfg *config.Config) []writer.FileOp {
	skillDir := transformerutil.SkillDir(".agents/skills", d.Name)
	var fm transformerutil.FmBuilder
	fm.Add("name", d.Name)
	// codex 不支持 when_to_use 字段，拼到 description 末尾让模型仍能感知触发线索
	fm.Add("description", transformerutil.MergeDescription(d.Description, d.WhenToUse))
	// agentskills 标准字段
	fm.Add("license", d.License)
	fm.Add("compatibility", d.Compatibility)
	fm.AddMap("metadata", d.Metadata)
	opts := transformerutil.MakeOpts(cfg, c.Name(), d.Path, false)
	skillMd := transformerutil.BuildMarkdownFile(skillDir+"/SKILL.md", fm.String(), d.Body, opts)
	return transformerutil.BuildSkillPackage(skillDir, skillMd, d.SkillFiles)
}

// buildCommandAsSkill 把 std command 降级写成 OpenAI agent skill
// 输出路径加 cmd- 前缀避免与同 name 的 skill 冲突
// description 含 slash 调用 hint 让模型理解这是 command-flavor skill
func (c *Codex) buildCommandAsSkill(d *parser.Document, cfg *config.Config) writer.FileOp {
	var fm transformerutil.FmBuilder
	fm.Add("name", "cmd-"+d.Name)
	desc := d.Description
	if desc == "" {
		desc = "Slash command: " + d.Name
	}
	desc += " (Invoke when user types /" + d.Name + " or asks to run " + d.Name + ")"
	fm.Add("description", desc)
	fm.Add("model", d.Model)
	opts := transformerutil.MakeOpts(cfg, c.Name(), d.Path, false)
	return transformerutil.BuildMarkdownFile(
		path.Join(".agents/skills", "cmd-"+d.Name, "SKILL.md"),
		fm.String(), d.Body, opts,
	)
}
