package transformer

import (
	"encoding/json"
	"fmt"
	"path"
	"strings"

	"std-ai/internal/config"
	"std-ai/internal/parser"
	"std-ai/internal/writer"
)

func init() {
	Register(&Codex{})
}

// Codex 是 OpenAI Codex CLI transformer
type Codex struct{}

// Name 返回 "codex"
func (c *Codex) Name() string { return "codex" }

// codexAGENTSMaxBytes 是 Codex 默认的 project_doc_max_bytes
const codexAGENTSMaxBytes = 32768

// Plan 计算输出
func (c *Codex) Plan(docs []*parser.Document, cfg *config.Config) (*writer.Plan, error) {
	plan := &writer.Plan{Target: c.Name()}

	// hooks 不依赖 docs，提前到 early return 之前确保仅 hooks 时也能输出
	if cfg.Hooks != nil && len(cfg.Hooks.Hooks) > 0 {
		plan.Files = append(plan.Files, c.buildHooksJSON(cfg.Hooks))
	}

	docs = FilterDocs(docs, c.Name())
	if len(docs) == 0 {
		return plan, nil
	}

	rules := FilterByType(docs, parser.TypeRules)
	skills := FilterByType(docs, parser.TypeSkills)
	commands := FilterByType(docs, parser.TypeCommands)
	SortDocs(rules)
	SortDocs(skills)
	SortDocs(commands)

	main, spilled := c.buildAGENTSMdWithCommands(rules, commands, cfg)
	plan.Files = append(plan.Files, main)
	for _, sp := range spilled {
		plan.Files = append(plan.Files, c.buildSpillRuleFile(sp, cfg))
	}

	for _, d := range skills {
		plan.Files = append(plan.Files, c.buildSkillFile(d, cfg)...)
	}

	// commands 降级为 skill：codex 自定义 prompt 已 deprecated 但支持 agent skills，
	// 把 std command 写为 .agents/skills/cmd-<n>/SKILL.md，description 加 slash 调用 hint
	for _, d := range commands {
		plan.Files = append(plan.Files, c.buildCommandAsSkill(d, cfg))
	}

	return plan, nil
}

// buildAGENTSMdWithCommands 拼 AGENTS.md，rules 超字节时返回溢出 docs；
// commands 段落始终追加在 AGENTS.md 末尾（让 aider / 其他读 AGENTS.md 的工具也能看到 slash 命令）
func (c *Codex) buildAGENTSMdWithCommands(rules, commands []*parser.Document, cfg *config.Config) (writer.FileOp, []*parser.Document) {
	op, spilled := c.buildAGENTSMd(rules, cfg)
	if len(commands) == 0 {
		return op, spilled
	}
	// 把 commands section 追加到 op.Content 的尾部 marker 之前
	commandsBlock := buildCommandsSection(commands)
	op.Content = injectBeforeFooter(op.Content, commandsBlock)
	return op, spilled
}

// buildCommandsSection 构造 ## Slash Commands 段落
func buildCommandsSection(commands []*parser.Document) string {
	var b strings.Builder
	b.WriteString("\n## Slash Commands\n\n")
	b.WriteString("以下命令可由用户输入 `/<name>` 触发，或在 LLM 对话中描述意图调用。\n\n")
	for _, d := range commands {
		fmt.Fprintf(&b, "### /%s\n\n", d.Name)
		if d.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", d.Description)
		}
		body := strings.TrimSpace(d.Body)
		if body != "" {
			b.WriteString(body)
			b.WriteString("\n\n")
		}
	}
	return b.String()
}

// injectBeforeFooter 把 block 插入到内容尾部，但在 stdagent close marker 之前
func injectBeforeFooter(content []byte, block string) []byte {
	s := string(content)
	// stdagent close marker 形如 "<!-- /Generated by stdagent -->\n"
	const marker = "<!-- /Generated by stdagent -->"
	idx := strings.LastIndex(s, marker)
	if idx < 0 {
		// 无 marker（inject=false），直接追加
		return []byte(s + block)
	}
	return []byte(s[:idx] + block + s[idx:])
}

// buildAGENTSMd 拼 AGENTS.md，超字节时返回溢出 docs
func (c *Codex) buildAGENTSMd(rules []*parser.Document, cfg *config.Config) (writer.FileOp, []*parser.Document) {
	opts := MakeOpts(cfg, c.Name(), "", true)
	header := writer.HeaderComment(opts)
	footer := writer.FooterMarker(opts)
	envelope := len(header) + len(footer) + 64
	budget := codexAGENTSMaxBytes - envelope
	if budget < 0 {
		budget = 0
	}

	var body strings.Builder
	body.WriteString("# Project AGENTS Manifest\n\n")

	included := []*parser.Document{}
	spilled := []*parser.Document{}
	for _, d := range rules {
		section := docToCodexSection(d)
		if body.Len()+len(section) > budget && len(included) > 0 {
			spilled = append(spilled, d)
			continue
		}
		body.WriteString(section)
		included = append(included, d)
	}

	if len(spilled) > 0 {
		body.WriteString("\n## Rules Reference\n\n")
		body.WriteString("AGENTS.md 已达字节上限，下列 rules 移至 .codex/rules/：\n\n")
		for _, d := range spilled {
			fmt.Fprintf(&body, "- [%s](%s)\n", d.Name, FilePath(".codex/rules", d.Name, ".md"))
		}
	}

	op := BuildMarkdownFile("AGENTS.md", "", body.String(), opts)
	return op, spilled
}

func docToCodexSection(d *parser.Document) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## %s\n\n", d.Name)
	if d.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", d.Description)
	}
	body := strings.TrimSpace(d.Body)
	if body != "" {
		b.WriteString(body)
		b.WriteString("\n\n")
	}
	return b.String()
}

func (c *Codex) buildSpillRuleFile(d *parser.Document, cfg *config.Config) writer.FileOp {
	opts := MakeOpts(cfg, c.Name(), d.Path, false)
	body := strings.TrimSpace(d.Body)
	if d.Description != "" {
		body = d.Description + "\n\n" + body
	}
	return BuildMarkdownFile(
		FilePath(".codex/rules", d.Name, ".md"),
		"", body, opts,
	)
}

// buildHooksJSON 输出 .codex/stdagent-hooks.json
//
// Codex 自身的 hooks schema 在公开文档中部分 UNKNOWN（仅知 hooks.json 路径与
// [features].codex_hooks 开关）。stdagent 输出 schema 镜像 std-ai 自身格式，
// 由用户在 codex 文档明确 schema 后手动转换或后续 v1.5 自动适配。
func (c *Codex) buildHooksJSON(hooks *config.HooksConfig) writer.FileOp {
	wrapper := struct {
		Version string                        `json:"version"`
		Hooks   map[string][]config.HookEntry `json:"hooks"`
	}{Version: hooks.Version, Hooks: hooks.Hooks}
	body, _ := json.MarshalIndent(wrapper, "", "  ")
	body = append(body, '\n')
	return writer.FileOp{
		Path:    ".codex/stdagent-hooks.json",
		Content: body,
		Reason:  "INFO: codex hooks schema 部分 UNKNOWN，stdagent 输出 std-ai 镜像格式；user 需对照 codex 文档手动转换或跑 `stdagent apply-hooks --target codex`",
	}
}

func (c *Codex) buildSkillFile(d *parser.Document, cfg *config.Config) []writer.FileOp {
	skillDir := SkillDir(".agents/skills", d.Name)
	var fm FmBuilder
	fm.Add("name", d.Name)
	// codex 不支持 when_to_use 字段，拼到 description 末尾让模型仍能感知触发线索
	fm.Add("description", MergeDescription(d.Description, d.WhenToUse))
	// agentskills 标准字段
	fm.Add("license", d.License)
	fm.Add("compatibility", d.Compatibility)
	fm.AddMap("metadata", d.Metadata)
	opts := MakeOpts(cfg, c.Name(), d.Path, false)
	skillMd := BuildMarkdownFile(skillDir+"/SKILL.md", fm.String(), d.Body, opts)
	return BuildSkillPackage(skillDir, skillMd, d.SkillFiles)
}

// buildCommandAsSkill 把 std command 降级写成 OpenAI agent skill
// 输出路径加 cmd- 前缀避免与同 name 的 skill 冲突
// description 含 slash 调用 hint 让模型理解这是 command-flavor skill
func (c *Codex) buildCommandAsSkill(d *parser.Document, cfg *config.Config) writer.FileOp {
	var fm FmBuilder
	fm.Add("name", "cmd-"+d.Name)
	desc := d.Description
	if desc == "" {
		desc = "Slash command: " + d.Name
	}
	desc += " (Invoke when user types /" + d.Name + " or asks to run " + d.Name + ")"
	fm.Add("description", desc)
	fm.Add("model", d.Model)
	opts := MakeOpts(cfg, c.Name(), d.Path, false)
	return BuildMarkdownFile(
		path.Join(".agents/skills", "cmd-"+d.Name, "SKILL.md"),
		fm.String(), d.Body, opts,
	)
}
