package transformer

import (
	"fmt"
	"strings"

	"github.com/StringKe/std-agent/internal/config"
	"github.com/StringKe/std-agent/internal/parser"
	"github.com/StringKe/std-agent/internal/transformer/protocol"
	"github.com/StringKe/std-agent/internal/transformer/transformerutil"
	"github.com/StringKe/std-agent/internal/writer"
)

func init() { Register(&Gemini{}) }

// Gemini 是 Google Gemini CLI transformer
//
// 特殊：commands 用 TOML 格式（`.gemini/commands/<n>.toml`），独一份方言。
// 因此 Plan 分两段处理：rules / skills / references / subagents 走 AgentsMD 协议
// 渲染 GEMINI.md，commands 走自己的 TOML 渲染。
type Gemini struct{}

// Name 返回 "gemini"
func (g *Gemini) Name() string { return "gemini" }

// Plan 计算输出
func (g *Gemini) Plan(docs []*parser.Document, cfg *config.Config) (*writer.Plan, error) {
	filtered := FilterDocs(docs, g.Name())

	nonCommands := make([]*parser.Document, 0, len(filtered))
	var commands []*parser.Document
	for _, d := range filtered {
		if d.Type == parser.TypeCommands {
			commands = append(commands, d)
			continue
		}
		nonCommands = append(nonCommands, d)
	}

	plan, err := protocol.AgentsMD{}.Plan(nonCommands, geminiAdapter, cfg)
	if err != nil {
		return nil, err
	}

	transformerutil.SortDocs(commands)
	for _, d := range commands {
		plan.Files = append(plan.Files, buildGeminiCommandTOML(d, cfg))
	}
	return plan, nil
}

// geminiAdapter 描述 Gemini 的根文件协议族行为。
//
// 渲染 GEMINI.md + 原生 skills（.gemini/skills/<n>/SKILL.md，v0.38+ GA 默认启用，
// https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/skills.md）。
// references / subagents 走 FallbackDir `.gemini/rules` 兜底。commands 不归
// protocol 处理（在 Plan 里提前剥离 TOML 渲染），所以这里 CommandsDir 留空、
// InjectCommandsToRoot 也保持 false。
var geminiAdapter = protocol.Adapter{
	Name:                 "gemini",
	RootFileName:         "GEMINI.md",
	NestedSupported:      true,
	SkillsDir:            ".gemini/skills",
	FallbackDir:          ".gemini/rules",
	InjectExplainer:      true,
	InjectStdaiTypeField: true,
	InjectTypeGlossary:   true,
}

// buildGeminiCommandTOML 渲染单条 command 为 `.gemini/commands/<name>.toml`
//
// Gemini 自定义 TOML 格式，含可选 description 字段与必填 prompt 字段。
func buildGeminiCommandTOML(d *parser.Document, cfg *config.Config) writer.FileOp {
	var b strings.Builder
	if cfg.Inject {
		fmt.Fprintf(&b,
			"# Generated by stdagent %s. Source: .stdai/standards/%s. Run `stdagent sync` to regenerate. Do not edit by hand.\n\n",
			transformerutil.Version(), d.Path)
	}
	if d.Description != "" {
		fmt.Fprintf(&b, "description = %q\n", d.Description)
	}
	prompt := strings.TrimSpace(d.Body)
	if prompt == "" {
		prompt = "(empty)"
	}
	fmt.Fprintf(&b, "prompt = '''\n%s\n'''\n", prompt)
	return writer.FileOp{
		Path:    transformerutil.FilePath(".gemini/commands", d.Name, ".toml"),
		Content: []byte(b.String()),
		Marker:  cfg.Inject,
	}
}
