package transformer

import (
	"fmt"
	"strings"

	"std-ai/internal/config"
	"std-ai/internal/parser"
	"std-ai/internal/writer"
)

func init() {
	Register(&Gemini{})
}

// Gemini 是 Google Gemini CLI transformer
type Gemini struct{}

// Name 返回 "gemini"
func (g *Gemini) Name() string { return "gemini" }

// Plan 计算输出
func (g *Gemini) Plan(docs []*parser.Document, cfg *config.Config) (*writer.Plan, error) {
	plan := &writer.Plan{Target: g.Name()}
	docs = FilterDocs(docs, g.Name())
	if len(docs) == 0 {
		return plan, nil
	}
	rules := FilterByType(docs, parser.TypeRules)
	commands := FilterByType(docs, parser.TypeCommands)
	SortDocs(rules)
	SortDocs(commands)

	plan.Files = append(plan.Files, g.buildGEMINIMd(rules, cfg))
	for _, d := range commands {
		plan.Files = append(plan.Files, g.buildCommand(d, cfg))
	}
	// skills 在 Gemini 上无原生概念，v1.0 不输出
	return plan, nil
}

func (g *Gemini) buildGEMINIMd(rules []*parser.Document, cfg *config.Config) writer.FileOp {
	opts := MakeOpts(cfg, g.Name(), "", true)
	body := JoinAGENTSStyle("Project GEMINI Manifest", rules)
	return BuildMarkdownFile("GEMINI.md", "", body, opts)
}

func (g *Gemini) buildCommand(d *parser.Document, cfg *config.Config) writer.FileOp {
	var b strings.Builder
	if cfg.Inject {
		fmt.Fprintf(&b,
			"# Generated by stdagent %s. Source: .stdai/standards/%s. Run `stdagent sync` to regenerate. Do not edit by hand.\n\n",
			transformerVersion, d.Path)
	}
	if d.Description != "" {
		fmt.Fprintf(&b, "description = %q\n", d.Description)
	}
	prompt := strings.TrimSpace(d.Body)
	if prompt == "" {
		prompt = "(empty)"
	}
	fmt.Fprintf(&b, "prompt = '''\n%s\n'''\n", prompt)
	return writer.FileOp{
		Path:    FilePath(".gemini/commands", d.Name, ".toml"),
		Content: []byte(b.String()),
		Marker:  cfg.Inject,
	}
}
